# ./ docker-compose.yaml
# traefik / jenkins container

version: '3.7'

services:
  traefik:
    image: traefik:v2.9
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/home/ubuntu/traefik/traefik.toml:/etc/traefik/traefik.toml:ro"
    ports: # Traefik 대시보드
      - "80:80"
      - "11118:8080"
    environment: # 서울 시간
      - TZ=Asia/Seoul
    networks:
      - jenkins-overlay-network
    deploy:
      placement:
        constraints:
          - node.role == manager

  jenkins:
    image: jenkins/jenkins:lts-jdk17
    ports:
      - "8080:8080"  # Jenkins에 직접 접근할 수 있는 포트
    volumes:
      - jenkins-data:/var/jenkins_home
    env_file:
      - .env
    environment:
      - TZ=Asia/Seoul
    networks:
      - jenkins-overlay-network
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.jenkins.rule=Host(`jenkins.boot-genie-test.click`)"
        - "traefik.docker.network=jenkins_jenkins-overlay-network"
        - "traefik.http.routers.jenkins.entrypoints=web"
        - "traefik.http.services.jenkins.loadbalancer.server.port=8080"
        - "traefik.http.routers.jenkins.service=jenkins"

networks:
  jenkins-overlay-network:
    driver: overlay
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  jenkins-data:
