[log]
  level = "INFO"

[entryPoints]
  [entryPoints.web]
    address = ":80"

[providers.docker]
  endpoint = "unix:///var/run/docker.sock"
  swarmMode = true
  exposedByDefault = false

[api]
  insecure = true

[http.services]
  [http.services.jenkins.loadBalancer]
    [[http.services.jenkins.loadBalancer.servers]]
      url = "http://jenkins:8080"
  
  [http.services.grafana.loadBalancer]
    [[http.services.grafana.loadBalancer.servers]]
      url = "http://grafana:3000"

[http.routers.jenkins]
  [http.routers.jenkins]
    rule = "Host(`jenkins.boot-genie-test.click`)"
    service = "jenkins"
    entryPoints = ["web"]
  
  [http.routers.grafana]
    rule = "Host(`grafana.boot-genie-test.click`)"
    service = "grafana"
    entryPoints = ["web"]